server:
  port: 8989

spring:
  jackson:
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      adjust-dates-to-context-time-zone: false

  application:
    name: forexrateaggregator

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/forexratedb}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:Mupezeni0102?}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC



  cache:
    type: redis
    redis:
      time-to-live: 3600000
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}

# Security Configuration
jwt:
  secret: ${JWT_SECRET:mySecretKey123456789012345678901234567890}
  expiration: 86400000 # 24 hours in milliseconds

# Forex API Configuration
forex:
  apis:
    exchangerate-api:
      url: https://api.exchangerate-api.com/v4/latest
#      access-key: ${EXCHANGERATE_API_KEY:9a0fb9c81c7468c5e1748e79}
      enabled: true
    fixer-api:
      url: https://data.fixer.io/api/latest
      access-key: ${FIXER_API_KEY:your_fixer_api_key}
      enabled: true
    currencylayer-api:
      url: https://api.currencylayer.com/live
      access-key: ${CURRENCYLAYER_API_KEY:your_currencylayer_api_key}
      enabled: true


  currencies:
    base: USD
    targets: GBP,ZAR


  markup: 0.10
  refresh-interval: 3600000 # 1 hour in milliseconds

# Resilience4j Configuration
resilience4j:
  circuitbreaker:
    instances:
      externalApi:
        register-health-indicator: true
        sliding-window-size: 10
        minimum-number-of-calls: 5
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 10s
        failure-rate-threshold: 50
        event-consumer-buffer-size: 10
  retry:
    instances:
      externalApi:
        max-attempts: 3
        wait-duration: 2s
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 2
  timelimiter:
    instances:
      externalApi:
        timeout-duration: 10s

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,circuitbreakers,ratelimiters
  endpoint:
    health:
      show-details: when-authorized
  health:
    circuitbreakers:
      enabled: true

# Logging Configuration
logging:
  level:
    co.zw.mupezeni.wiremit: INFO
    org.springframework.security: DEBUG
    org.springframework.web: INFO
#    org.hibernate.SQL: DEBUG
#    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

